// <auto-generated />
namespace PeriodicalLiterature.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class renamefeld : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(renamefeld));
        
        string IMigrationMetadata.Id
        {
            get { return "201902251838511_renamefeld"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
